### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by jimmaaay** [icetee/remote-ftp#366]
When trying to use watch functionality I get the following.

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:8

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /Users/jimmy/.atom/packages/Remote-FTP/lib/client.js:746:25
    at Array.forEach (native)
    at Client.module.exports.Client.watch.addListeners (/Users/jimmy/.atom/packages/Remote-FTP/lib/client.js:745:14)
    at emitNone (events.js:72:20)
    at Client.emit (events.js:166:7)
    at ConnectorSFTP.<anonymous> (/Users/jimmy/.atom/packages/Remote-FTP/lib/client.js:283:9)
    at /Users/jimmy/.atom/packages/Remote-FTP/lib/connectors/sftp.js:56:16
    at SFTPStream.onReady (/Users/jimmy/.atom/packages/Remote-FTP/node_modules/ssh2/lib/client.js:758:9)
    at SFTPStream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at SFTPStream.emit (events.js:166:7)
    at SFTPStream._transform (/Users/jimmy/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:340:14)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/jimmy/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (/Users/jimmy/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:146:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (/Users/jimmy/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3163:10)
    at SSH2Stream._transform (/Users/jimmy/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/jimmy/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by jimmaaay** [comment]
I've created a Pull Request fixing this issue.

**Comment by kunokdev** [comment]
How do you fix  this issue?

**Comment by kunokdev** [comment]
I changed client.js file just like you changed it in your pull request and the error is still present.

**Comment by kunokdev** [comment]
I fixed this problem by removing placeholder from "watch" property in .ftpconfig file object.

**Comment by derekcavaliero** [comment]
I am receiving the same error. It shouldn't be requiring a string there, the configuration options mentions that it should be an array of different files. Configuration array shown below:

![screen shot 2016-05-12 at 12 15 37 pm](https://cloud.githubusercontent.com/assets/5420084/15221883/46dff42c-183b-11e6-8028-d4b4e3856883.png)

Also, on a somewhat related note, is it possible to have it watch an entire directory for changes? For example:

`"watch": [ "/dist/css/**/*.css", "/dist/js/**/*.js" ]`

That would be awesome, but I don't see any mention of it in the documentation.

Thanks! & Awesome package!

**Comment by robhuska** [comment]
@jimmaaay That fix worked for me! I no longer get an error when I have an array of files!

and +1 to @derekcavaliero's request for the acceptance of globs in the watch array! Or even just an entire directory...

**Comment by wouter1407** [comment]
I'm still getting this error, in my .ftpconfig file i have it like this:

"watch": ["./styles/css/style.css"]

Using Gulp to compile en minify (also watch). Is there a solution yet?

**Comment by jimmaaay** [comment]
@wouter1407 What version of remote ftp are you using?

**Comment by wouter1407** [comment]
@jimmaaay I'm using 0.8.3, checked for updates but Atom says there are none.

**Comment by jimmaaay** [comment]
@wouter1407 could you try uninstalling and reinstalling remote ftp, then if you still get the error can you paste it into the thread.

**Comment by RonHolt** [comment]
@jimmaaay 
I'm getting this error too now.  I tried uninstalling remote-ftp & reinstalling it and still get the error. 

This is what I have for the watch line:
    "watch": ["./style.css"]

When I try the following (removing the leading '.') it connects but it says "Could not find /style.css to watch" even though that file is in my project's root folder.
    "watch": ["/style.css"]

When I try the following, it gives me the "Path must be a string..." error again.
    "watch": ["style.css"]

Here is the error report:

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:8

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /Users/ron/.atom/packages/Remote-FTP/lib/client.js:746:25
    at Array.forEach (native)
    at Client.module.exports.Client.watch.addListeners (/Users/ron/.atom/packages/Remote-FTP/lib/client.js:745:14)
    at emitNone (events.js:72:20)
    at Client.emit (events.js:166:7)
    at ConnectorSFTP.<anonymous> (/Users/ron/.atom/packages/Remote-FTP/lib/client.js:283:9)
    at /Users/ron/.atom/packages/Remote-FTP/lib/connectors/sftp.js:56:16
    at SFTPStream.onReady (/Users/ron/.atom/packages/Remote-FTP/node_modules/ssh2/lib/client.js:758:9)
    at SFTPStream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at SFTPStream.emit (events.js:166:7)
    at SFTPStream._transform (/Users/ron/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:340:14)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/ron/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (/Users/ron/.atom/packages/Remote-FTP/node_modules/ssh2/lib/Channel.js:146:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (/Users/ron/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3163:10)
    at SSH2Stream._transform (/Users/ron/.atom/packages/Remote-FTP/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
```

### Commands

```
     -4:26.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:24.7.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -4:24 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:20.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:42.1.0 remote-ftp:disconnect (atom-text-editor.editor.is-focused)
  2x -3:15.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:15.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:12.1.0 core:save (atom-text-editor.editor.is-focused)
     -3:05.5.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
  2x -1:15.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "remote-edit"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
atom-jshint, v2.0.0

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
@GitarMan That's very odd. Could you try amending /lib/client.js and before line 746 add in a `console.log(dir, watch)` ( see below ). Then restart atom. 

When it's restarted go to View > Developer > Toggle Developer Tools. Then when you try connecting to your server it should log both of the properties, if you could let me know what they return when an error is thrown that would be great.

```
watchData.forEach(function(watch) {
                                console.log(dir, watch); // this 
                var fileName = Path.resolve(dir, watch);
```

**Comment by EJ207** [comment]
having this issue as well

**Comment by jimmaaay** [comment]
@EJ207, are you still having this issue in the latest update?

**Comment by robhuska** [comment]
Problems have all been resolved for me! For a while I was about to ditch this plugin because it was happening very consistenly that processed css files and maps were being dropped. Now we are good. But I saw you also added the ability to just add a directory, could you give and example of what we should do to have that work?

**Comment by jimmaaay** [comment]
@robhuska Sure, all you need to do is reference the directory e.g 

```
"watch":[
    "./js"
]
```

This will reference the js directory in the root of the project folder. 

Edit: Will update the configurations in the read me

**Comment by jimmaaay** [comment]
Will need to remove the space between the dot and forward slash. Formatting on mobile isn't the easiest

**Comment by jimmaaay** [comment]
This should be sorted now, if anyone is having issues with this still leave a commend and I'l re open. Also if anyone has questions about the watch functionality just open another issue.
